name    'ghoneycutt-java'
version '0.1.0'
source 'git://github.com/ghoneycutt/puppet-module-java.git'
author 'ghoneycutt'
license 'Apache License, Version 2.0'
summary 'manage java client'
description 'manage java client'
project_page 'https://github.com/ghoneycutt/puppet-module-java'
